"""empty message

Revision ID: 7ca288f28e00
Revises: 86d6a617f84c
Create Date: 2018-01-05 09:52:23.923000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca288f28e00'
down_revision = '86d6a617f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tier', sa.Column('paypal_button_link', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'tier', ['paypal_button_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_column('tier', 'paypal_button_link')
    # ### end Alembic commands ###
