"""empty message

Revision ID: 86d6a617f84c
Revises: ecbeeea53915
Create Date: 2018-01-05 09:47:19.268714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d6a617f84c'
down_revision = 'ecbeeea53915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
