"""empty message

Revision ID: cdef345473b6
Revises: 7ca288f28e00
Create Date: 2018-01-17 08:57:53.587306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdef345473b6'
down_revision = '7ca288f28e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iprofile_data', sa.Column('posts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iprofile_data', 'posts_count')
    # ### end Alembic commands ###
