"""empty message

Revision ID: ecbeeea53915
Revises: e87c9161ec8b
Create Date: 2018-01-05 09:41:35.496361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbeeea53915'
down_revision = 'e87c9161ec8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('min_accounts', sa.Integer(), nullable=False),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('price_pm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('tier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tier', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tier_id')
    op.drop_table('tier')
    # ### end Alembic commands ###
